### ISSUE TITLE
Compile error on Mac OS X: Error: undefined identifier activeInstrument

### ISSUE THREAD

**Issue by Grrrolf** [theyamo/CheeseCutter#15]
I get the following error while compiling the regular CC (with make -f Makefile.mac):

ldc2 -I./src -J./src/c64 -J./src/font -d -O2 -c -of=src/ui/ui.o src/ui/ui.d 
src/ui/ui.d(587): Error: undefined identifier activeInstrument
make: **\* [src/ui/ui.o] Error 1

The code:

```
else if(key.mods & KMOD_SHIFT) {
    version(OSX) {
        if(key.raw == SDLK_EQUALS) {
            instable.stepRow(1);
            activeInstrument = instable.row;
         }
    }
} 
```

When I change the `activeInstrument = instable.row;` to `state.activeInstrument = instable.row;`, it won't give a compile error and finishes without errors.

**Comment by theyamo** [comment]
fixed
