### ISSUE TITLE
It is not possible to enter a hyphen (the '-' sign) in instrument names.

### ISSUE THREAD

**Issue by Grrrolf** [theyamo/CheeseCutter#17]
It is not possible to use a hyphen '-' sign in the instrument name in the instrument table. When I presse '-', it jumpst to the previous instrument and makes this instrument the active/selected one.

This problem does not occur when I enter (via alt+t) the song title and such.

**Comment by BerggreenDK** [comment]
it's not possible to use '+' either.

I usually put my KICK in instrument 01 and SNARE in instrument 02..

and in instrument 0 I use KICK + BASS.. which I cant.. as + makes the cursor jump out

**Comment by theyamo** [comment]
fixed.

**Comment by Grrrolf** [comment]
Tested on mac and indeed fixed.
