### ISSUE TITLE
Base octave keys

### ISSUE THREAD

**Issue by Grrrolf** [theyamo/CheeseCutter#18]
When I change the base octave to 0, I cannot enter the lower C and D notes (keys z and x). CC creates a `--- 02 --` and `+++ 02 --` instead of `C-0 02 --` and `D-0 02 --` in the sequence editor.

**Comment by theyamo** [comment]
First 3 values are reserved for rest, gate off and gate on, overriding the note values therein. It's still possible to play the notes by transposing the track.
