### ISSUE TITLE
2SID (2.8) - CTRL+F9 has a bad placement for both debug windows

### ISSUE THREAD

**Issue by BerggreenDK** [theyamo/CheeseCutter#19]
I think it would be more useful if the two SID chips output were placed accordingly to their channels, aka above each of the two blocks. 

So starting from left with channel 1 has a left aligned register debug window above and the other chip (which ever is right side and channel 4,5,6) is above that them, starting at channel 4..

Tell me which file to position these in, and I can change it.

**Comment by Grrrolf** [comment]
On mac it looks even worse than you describe: 
![screenshot](http://ammo.home.xs4all.nl/cheese/2sid-ctrl-f9-placement.png)

**Comment by BerggreenDK** [comment]
Thats actually exactly as it looks on Windows too. just more green?

**Comment by theyamo** [comment]
It seems there's some incompatibility in how the YUV image is rendered. Or maybe SDL is fecked up. Anyway, I can't fix the Mac colors because I don't own one. If someone wants to give a try, I can point to where to look.

**Comment by theyamo** [comment]
As for the registers display bug, yes, must fix that soonish.

**Comment by theyamo** [comment]
Fixed
