### ISSUE TITLE
Pointer value of starting row not correct when inserting new rows in Pulse and Filter tables?

### ISSUE THREAD

**Issue by Grrrolf** [theyamo/CheeseCutter#20]
This bahaviour applies to both the pulse and filter table.
When I insert a new row, the following happens:

Orignial table:

```
Filter
00:7F 00 FF 7F
01:90 F1 83 02
02:00 00 C6 03
03:00 00 09 04
04:00 00 07 05
05:00 00 05 7F
06:00 00 00 00
07:00 00 00 00
08:00 00 00 00
```

The table after inserting 1 row after row 01:

```
Filter
00:7F 00 FF 7F
01:90 F1 83 03 <-- is changed to the row number of the original next row.
02:00 00 00 00
03:00 00 C6 04
04:00 00 09 05
05:00 00 07 06
06:00 00 05 7F
06:00 00 00 00
07:00 00 00 00
08:00 00 00 00
```

It seems that the value of the pointer in row 01 is changed to the new number of the original next row. I would expect that the pointer value of row 01 stays the same. Now I have to change the value manually so that it points to row 02 again. CC seems to keep track of the new row number of the shifted row and puts that in the first row of the filter.

The table after inserting even more now rows looks like:

```
Filter
00:7F 00 FF 7F
01:90 F1 83 06 <-- changed to row number of the original next row.
02:00 00 00 00
03:00 00 00 00
04:00 00 00 00
05:00 00 00 00
06:00 00 C6 07
07:00 00 09 08
08:00 00 07 09
09:00 00 05 7F
0A:00 00 00 00
0B:00 00 00 00
0C:00 00 00 00
```

With this behaviour the original filter will not break until you manually changes the pointer values :-)

**Comment by theyamo** [comment]
It's working correctly. The idea is that you do "absolute jumps" only when you want to wrap or end your program. If you leave 4th column to 00, the next row always chosen automatically. If your program had been like this:

```
01:90 F1 83 00
02:00 00 C6 00
03:00 00 09 00
04:00 00 07 00
05:00 00 05 7F
```

Then, if you inserted empty row somewhere inside that filterprogram, your new row would not get skipped.

**Comment by Grrrolf** [comment]
Ah, that's my bad then!! Just now I checked the reference guide on the CC homepage and I feel a bit silly now. It says it right there ;-)
