### ISSUE TITLE
BUG! Fullscreen not accessable anymore

### ISSUE THREAD

**Issue by BerggreenDK** [theyamo/CheeseCutter#28]
CC 2.8 Jul 09 2015 - ALT+ENTER does NOT make CC go into fullscreen as we are used to. We can maximize the window, but not gain fullscreen.

**Comment by Grrrolf** [comment]
Indeed alt+enter does no longer work. Resize/maximise window does not work at all om mac os x. ./ccutter -f does open full screen and alt+enter changes it back to windowed mode. I tested this on the July 14 2015 CC2.8 build/source.

**Comment by BerggreenDK** [comment]
Yeah, the new "windowed mode" is a "nice option" if only I could decide if I wanted it or not. Thinking of going back to previous version until we get fullscreen back. I dont like the fact that I can see Windows taskbar in the bottom of my view and window icons in the top bar. Fullscreen for me, please :-)

IF we want to have both, I would recommend that -windowed could be used as param to ccutter.exe and that would enable this windowed behavior. It would be easy to have two shortcuts to the editor and switching would be a matter of saving tune, and opening the other version and load, but I would probably never switch.

**Comment by theyamo** [comment]
Full screen mode should now be exactly as before. SDL_FULLSCREEN and SDL_RESIZABLE seemed to act weird together.
