### ISSUE TITLE
makefile on linux fails

### ISSUE THREAD

**Issue by alexmyczko** [theyamo/CheeseCutter#35]
Maybe mention in README.md that 

# make
acme -f cbm --outfile src/c64/player.bin src/c64/player_v4.acme
make: acme: Command not found

one can get
https://github.com/meonwax/acme build and install it

and then this is as far as i could get (i386):
# make
ldc2 -O2 -I./src -J./src/c64 -J./src/font -c -of=src/ct2util.o src/ct2util.d
Makefile:75: recipe for target 'src/ct2util.o' failed
make: *** [src/ct2util.o] Illegal instruction

**Comment by theyamo** [comment]
That might be ldc2 bug. Which version are you using? Also be sure to do "make clean" before building, in case you have old object files lying around.

If you have other D compilers available, you could try build with them.

For dmd, make -f Makefile
For gdc, make -f Makefile.gdc

AFAIK these do not work on MacOS however.

**Comment by alexmyczko** [comment]
sorry saw your answer just now. i will give it a try...<am on linux) trying to build a debian package...

**Comment by alexmyczko** [comment]
Where is the Makefile.gdc ?

**Comment by alexmyczko** [comment]
dmd is not in debian officially, but I tried, and it gets a bit further (then fails, on i386, 32-bit Linux):

dmd  -I./src -J./src/c64 -J./src/font -O -c -ofsrc/ui/dialogs.o  src/ui/dialogs.d
./src/derelict/sdl/sdltypes.d(139): Deprecation: instead of C-style syntax, use D-style syntax void function(SDL_AudioCVT* cvt, Uint16 format)[10] filters
./src/derelict/sdl/sdltypes.d(210): Deprecation: instead of C-style syntax, use D-style syntax SDL_CDtrack[SDL_MAX_TRACKS + 1] track
./src/derelict/sdl/sdltypes.d(820): Deprecation: instead of C-style syntax, use D-style syntax Uint8*[2] save
./src/derelict/util/sharedlib.d(84): Deprecation: module std.c.linux.linux is deprecated - Import the appropriate core.sys.posix.* modules instead
src/ui/dialogs.d(411): Error: no property 'sort' for type 'char[][]'
src/ui/dialogs.d(414): Error: no property 'sort' for type 'char[][]'
Makefile.dmd:70: recipe for target 'src/ui/dialogs.o' failed
make: *** [src/ui/dialogs.o] Error 1

**Comment by modeler** [comment]
I got that same error on Ubuntu 18.04, it's an ldc issue. If I installed the Debian packages from stretch-backports, it compiled fine:

https://packages.debian.org/stretch-backports/amd64/ldc
https://packages.debian.org/stretch-backports/amd64/libphobos2-ldc-dev
https://packages.debian.org/stretch-backports/amd64/libphobos2-ldc72

These provide LDC 1.2.0, while the default repos provide LDC 1.8.0.

**Comment by snq-** [comment]
> src/ui/dialogs.d(411): Error: no property 'sort' for type 'char[][]'
> src/ui/dialogs.d(414): Error: no property 'sort' for type 'char[][]'

adding the following line to dialogs.d should do the trick:

`import std.algorithm : sort;`

**Comment by alexmyczko** [comment]
well now i get:

$ make
ldc2 -O2 -I./src -J./src/c64 -J./src/font -c -of=src/ct2util.o src/ct2util.d
make: *** [Makefile:75: src/ct2util.o] Illegal instruction

I've got: 
ldc            1:1.11.0-2   i386         LLVM D Compiler

**Comment by Grrrolf** [comment]
Try using ldc2 1.1.1. Anything newer won't compile the sources on macOS. So, perhaps on Linux neither.

**Comment by snq-** [comment]
[so here's what I did](https://gist.githubusercontent.com/snq-/2b1d35926f9dbd83dd8257d055eb074c/raw/0db05bb5e78a5fb369eb79431b6f5cd4b1fe7f34/ccbuild.txt)

**Comment by alexmyczko** [comment]
> [so here's what I did](https://gist.githubusercontent.com/snq-/2b1d35926f9dbd83dd8257d055eb074c/raw/0db05bb5e78a5fb369eb79431b6f5cd4b1fe7f34/ccbuild.txt)

thanks, now i can progress. acme package already ready for debian...

**Comment by alexmyczko** [comment]
i think only the linking for ccutter failes now (ct2util gets built):
gdc -O2 -o ccutter src/derelict/util/compat.o src/derelict/util/sharedlib.o src/derelict/util/exception.o src/derelict/util/loader.o src/derelict/util
/wintypes.o src/derelict/util/xtypes.o src/derelict/sdl/sdl.o src/derelict/sdl/net.o src/derelict/sdl/ttf.o src/derelict/sdl/mixer.o src/derelict/sdl/
image.o src/derelict/sdl/sdlfuncs.o src/derelict/sdl/sdltypes.o src/derelict/sdl/macinit/CoreFoundation.o src/derelict/sdl/macinit/DerelictSDLMacLoade
r.o src/derelict/sdl/macinit/ID.o src/derelict/sdl/macinit/MacTypes.o src/derelict/sdl/macinit/NSApplication.o src/derelict/sdl/macinit/NSArray.o src/
derelict/sdl/macinit/NSAutoreleasePool.o src/derelict/sdl/macinit/NSDictionary.o src/derelict/sdl/macinit/NSEnumerator.o src/derelict/sdl/macinit/NSEv
ent.o src/derelict/sdl/macinit/NSGeometry.o src/derelict/sdl/macinit/NSMenu.o src/derelict/sdl/macinit/NSMenuItem.o src/derelict/sdl/macinit/NSNotific
ation.o src/derelict/sdl/macinit/NSObject.o src/derelict/sdl/macinit/NSProcessInfo.o src/derelict/sdl/macinit/NSString.o src/derelict/sdl/macinit/NSZo
ne.o src/derelict/sdl/macinit/runtime.o src/derelict/sdl/macinit/SDLMain.o src/derelict/sdl/macinit/selectors.o src/derelict/sdl/macinit/string.o src/
audio/audio.o src/audio/player.o src/audio/timer.o src/audio/callback.o src/ct/purge.o src/ct/base.o src/ct/dump.o src/com/fb.o src/com/cpu.o src/com/
kbd.o src/com/session.o src/com/util.o src/main.o src/ui/tables.o src/ui/dialogs.o src/ui/ui.o src/ui/input.o src/ui/help.o src/seq/seqtable.o src/seq
/tracktable.o src/seq/trackmap.o src/seq/fplay.o src/seq/sequencer.o src/audio/resid/filter.o src/audio/resid/residctrl.o src/resid/envelope.o src/res
id/extfilt.o src/resid/filter.o src/resid/w6_ps_.o src/resid/w6_pst.o src/resid/w6_p_t.o src/resid/w6__st.o src/resid/w8_ps_.o src/resid/w8_pst.o src/
resid/w8_p_t.o src/resid/w8__st.o src/resid/pot.o src/resid/sid.o src/resid/voice.o src/resid/wave.o src/resid-fp/envelopefp.o src/resid-fp/extfiltfp.
o src/resid-fp/filterfp.o src/resid-fp/potfp.o src/resid-fp/sidfp.o src/resid-fp/versionfp.o src/resid-fp/voicefp.o src/resid-fp/wavefp.o -L-ldl -L-ls
tdc++                                                                                                                                                 
/usr/bin/ld: src/audio/resid/residctrl.o: in function `sid_close':                                                                                    
residctrl.cpp:(.text+0x1e): undefined reference to `operator delete(void*, unsigned long)'                                                            
/usr/bin/ld: src/audio/resid/residctrl.o: in function `sid_init':                                                                                     
residctrl.cpp:(.text+0x266): undefined reference to `operator new(unsigned long)'                                                                     
/usr/bin/ld: residctrl.cpp:(.text+0x28e): undefined reference to `operator new(unsigned long)'                                                        
/usr/bin/ld: src/audio/resid/residctrl.o: in function `sid_close':                                                                                    
residctrl.cpp:(.text+0x40): undefined reference to `operator delete(void*, unsigned long)'                                                            
/usr/bin/ld: src/audio/resid/residctrl.o: in function `sid_init.cold.0':                                                                              
residctrl.cpp:(.text.unlikely+0x9): undefined reference to `operator delete(void*, unsigned long)'

**Comment by snq-** [comment]
for some reason, you seem to have "LIBS=-L-ldl -L-lstdc++" instead of "LIBS=-ldl -lstdc++" in your - probably hand-edited - makefile

**Comment by alexmyczko** [comment]
Great, now there's debian packages ready to use (or rebuild) on your Debian/Ubuntu:

http://sid.ethz.ch/debian/cheesecutter/
http://sid.ethz.ch/debian/acme/

**Comment by alexmyczko** [comment]
thanks for the help!
