### ISSUE TITLE
Can't change base octave

### ISSUE THREAD

**Issue by sommerper** [theyamo/CheeseCutter#36]
I'm trying to learn CheeseCutter and so far it's going ok.

For some reason I have an issue changing the base octave from 3.
Then manual states in the note column press + or -.

When i press F6 and then "-" it goes down one instrument as if I had pressed minus on the keypad.
If I press + nothing happens.

I'm using an american layout if that helps.

Thanks

**Comment by Grrrolf** [comment]
Give < and > a try. This works for me on my mac. Perhaps this also works for you. Make sure that you're in the sequencer/editor (alt+v) and not in the instrument table.

**Comment by sommerper** [comment]
That works. Thanks!
