### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by alexmyczko** [theyamo/CheeseCutter#39]
What's wrong when it crashes like this?

```
[~]$ ccutter 
Crashed! Saving backup...
std.file.FileException@/usr/lib/gcc/x86_64-linux-gnu/8/include/d/std/file.d(1639): /home/kilobyte/.steampath: No such file or directory
----------------
0x55c918d5855a @trusted bool std.file.cenforce!(bool).cenforce(bool, const(char)[], const(char)*, immutable(char)[], ulong)
	???:0
0x55c918d6bfa3 ???
	???:0
0x55c918d6838d ???
	???:0
0x55c918d67358 ???
	???:0
0x55c918d66358 ???
	???:0
0x55c918d5e1a4 ???
	???:0
0x55c918d70d6b ???
	???:0
0x55c918d725b7 ???
	???:0
0x55c918d57275 ???
	???:0
0x7f44e4dbec9e ???
	???:0
0x7f44e4dbee3d ???
	???:0
0x7f44e4dbf1ba ???
	???:0
0x7f44e4dbee3d ???
	???:0
0x7f44e4dbefe4 _d_run_main
	???:0
0x7f44e4819b16 __libc_start_main
	../csu/libc-start.c:310
0x55c918d0bb09 ???
	???:0
0xffffffffffffffff ???
	???:0
```

**Comment by theyamo** [comment]
From the top of my head (can't try it out myself right now), the issue is likely related to the directory  name beginning with period (.). I recall the std or some other component had problems handling such dirs, so the file selector normally filters those away. I assume you typed the path yourself in the field in the file selector dialog, instead of browsing there (cos that shoudn't be possible)?

**Comment by theyamo** [comment]
Hmm, likely the above guess is incorrect. I need to see if I can reproduce it later.

**Comment by kilobyte** [comment]
(Original reporter here.)  I did not type any path, it's not in my ENV, etc.  Just tried to start ccutter — first from the .desktop (no apparent effect; obvious with the crash) then from command line, with no arguments.

There is a dangling symlink by that name in my home dir, though.

**Comment by chenz** [comment]
Can confirm that cheesecutter crashes when there are dangling symlinks in the cwd.
```
mkdir /tmp/test
cd /tmp/test
ln -s foo bar
ccutter

Crashed! Saving backup...
std.file.FileException@/usr/lib/gcc/x86_64-linux-gnu/8/include/d/std/file.d(1639): /tmp/test/bar: No such file or directory
```
There is also a file `_backup.ct` left in the cwd after the crash.

**Comment by kilobyte** [comment]
Aye, that's enough to cause the crash, and the backup file.
