### ISSUE TITLE
fails to build with GCC-9

### ISSUE THREAD

**Issue by alexmyczko** [theyamo/CheeseCutter#44]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925651

**Comment by theyamo** [comment]
I fixed some imports and tried building it with the latest Debian snapshot. Seems to work. I also set gdc as the default compiler again so package maintainer edits shouldn't be necessary.

**Comment by pezz** [comment]
I know this isn't really related, but I didn't want to make a new bug, but also unable to build on Arch Linux right now, but I think it's a general gdc issue so I lodged this:

https://bugs.archlinux.org/task/63067

Just an FYI anyway, cheers.

**Comment by alexmyczko** [comment]
Many thanks! https://buildd.debian.org/status/package.php?p=cheesecutter
