### ISSUE TITLE
build problem with gcc 11

### ISSUE THREAD

**Issue by alexmyczko** [theyamo/CheeseCutter#56]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=984009

**Comment by cpaelzer** [comment]
FYI this is due to an intended removal:
 https://dlang.org/changelog/2.075.0.html#pattern-deprecate

You actually have the fix already applied via
 https://github.com/theyamo/CheeseCutter/commit/68d6518f0e6249a2a5d122fc80201578337c1277

**Comment by alexmyczko** [comment]
and what about https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=994561 ?
